### ISSUE TITLE
renovate-bot does not commit with messages that follow the proper format

### ISSUE THREAD

**Issue by aleccool213** [Yolk-HQ/next-utils#24]
## Describe the bug

`chore` should be `build`

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type

## To Reproduce

Check out our releases, semantic-release does not release renovate prs

## Expected behaviour

A clear and concise description of what the expected results are.

**Comment by elliottsj** [comment]
[semantic-release itself uses `chore(package)`](https://github.com/semantic-release/semantic-release/commit/195e5b18c7af8907ce6ee357171f558d6fa2059b)

The [default conventional-changelog implementation for semantic-release](https://github.com/conventional-changelog/conventional-changelog/tree/b9f50573f292ea29ff51627646ca7825bf182d52/packages/conventional-changelog-angular#type) says:

>If the prefix is `feat`, `fix` or `perf`, it will appear in the changelog.

>Other prefixes are up to your discretion.

So there is no effect to how semantic-release behaves whether we choose `chore` or `build`. This is more of a dev experience / convention issue than a bug.

**Comment by aleccool213** [comment]
True 👌 Thanks for investigating.
